name: wifi_info_flutter_tizen
description: Tizen implementation of the wifi_info_flutter plugin
version: 1.0.0
homepage: https://github.com/flutter-tizen/plugins

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: WifiInfoFlutterTizenPlugin
        fileName: wifi_info_flutter_tizen_plugin.h

dependencies:
  flutter:
    sdk: flutter
  wifi_info_flutter_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"
