name: wifi_info_flutter_tizen
description: A new flutter plugin project.
version: 1.0.0
homepage: https://github.com/flutter-tizen/plugins

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: WifiInfoFlutterTizenPlugin
        fileName: wifi_info_flutter_tizen_plugin.h

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  wifi_info_flutter_platform_interface: ^1.0.0

dev_dependencies:
  mockito: ^4.1.1
  plugin_platform_interface: ^1.0.0
  flutter_test:
    sdk: flutter

