name: wifi_info_flutter_tizen_example
description: Demonstrates how to use the wifi_info_flutter_tizen plugin.
publish_to: 'none'

dependencies:
  connectivity: ^2.0.2
  connectivity_tizen:
    path: ../../connectivity/
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  integration_test: ^1.0.1
  integration_test_tizen:
    path: ../../integration_test/
  wifi_info_flutter: ^1.0.1
  wifi_info_flutter_tizen:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"
